# Generated by Django 5.2.4 on 2025-08-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"]},
        ),
    ]
