# Generated by Django 5.2.4 on 2025-08-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
    ]
