# Generated by Django 5.2.4 on 2025-08-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_review_ratings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="description",
            new_name="comment",
        ),
    ]
