# Generated by Django 5.2.4 on 2025-08-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_review_date_review_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
